# Generated by Django 3.2.7 on 2021-09-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userimage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
