# Generated by Django 3.2.7 on 2021-09-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0004_delete_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
