# Generated by Django 3.2.7 on 2021-09-16 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210913_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(blank=True, max_length=500)),
                ('child_talk_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('talk_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to='main.user')),
            ],
        ),
    ]
