# Generated by Django 3.2.7 on 2021-09-16 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210917_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
