# Generated by Django 3.2.7 on 2021-09-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_talk_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='child_talk_id',
        ),
    ]
