# Generated by Django 3.2.7 on 2021-09-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_talk_child_talk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talk_from',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupImage',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
