# Generated by Django 3.2.7 on 2021-09-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_group_groupimage_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to='main.user'),
        ),
    ]
