# Generated by Django 3.2.7 on 2021-09-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_talk_talk_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to='main.user'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to='main.user'),
        ),
    ]
