# Generated by Django 3.2.7 on 2021-10-20 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210926_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
