# Generated by Django 3.2.7 on 2021-10-02 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_userimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='child_talk_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
