# Generated by Django 3.2.7 on 2021-10-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='child_talk_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talk_from',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talk_to',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='time',
        ),
    ]
