# Generated by Django 3.2.7 on 2021-10-31 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211031_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='child_talk_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
