# Generated by Django 3.2.7 on 2021-10-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_talk_child_talk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='child_talk_id',
        ),
    ]
