# Generated by Django 3.2.7 on 2021-10-31 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_talk_child_talk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
