# Generated by Django 3.2.7 on 2021-10-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_topic_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic',
        ),
    ]
