# Generated by Django 3.2.7 on 2021-10-31 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
