# Generated by Django 3.2.7 on 2021-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.JSONField(default={}),
        ),
    ]
