# Generated by Django 3.2.7 on 2021-11-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='child_talk_id',
            field=models.JSONField(default={}),
        ),
    ]
