# Generated by Django 3.2.7 on 2021-11-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_topic_talk_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='talk_from',
        ),
    ]
