# Generated by Django 3.2.7 on 2021-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_topic_talk_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='parent_talk_id',
            field=models.IntegerField(null=True),
        ),
    ]
