# Generated by Django 3.2.7 on 2021-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_talk_parent_talk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='topic',
            field=models.JSONField(default={}),
        ),
    ]
